{{- if .Values.deployment.poller.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oneview-pagerduty-bridge.fullname" . }}-poller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oneview-pagerduty-bridge.labels" . | nindent 4 }}
    component: poller
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.deployment.poller.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.deployment.poller.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.deployment.poller.replicaCount }}
  selector:
    matchLabels:
      {{- include "oneview-pagerduty-bridge.selectorLabels" . | nindent 6 }}
      component: poller
  template:
    metadata:
      labels:
        {{- include "oneview-pagerduty-bridge.selectorLabels" . | nindent 8 }}
        component: poller
        {{- with .Values.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.deployment.poller.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ .Values.config.port | quote }}
        prometheus.io/path: "/metrics"
        {{- with .Values.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.deployment.poller.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "oneview-pagerduty-bridge.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}-poller
        image: {{ include "oneview-pagerduty-bridge.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.config.port }}
          protocol: TCP
        env:
        {{- range $key, $value := .Values.deployment.poller.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        envFrom:
        - configMapRef:
            name: {{ include "oneview-pagerduty-bridge.fullname" . }}-config
        {{- if .Values.externalSecrets.enabled }}
        - secretRef:
            name: {{ .Values.externalSecrets.externalSecret.secretName }}
            optional: true
        {{- end }}
        resources:
          {{- toYaml .Values.deployment.poller.resources | nindent 10 }}
        {{- if .Values.deployment.poller.livenessProbe.enabled }}
        livenessProbe:
          {{- omit .Values.deployment.poller.livenessProbe "enabled" | toYaml | nindent 10 }}
        {{- end }}
        {{- if .Values.deployment.poller.readinessProbe.enabled }}
        readinessProbe:
          {{- omit .Values.deployment.poller.readinessProbe "enabled" | toYaml | nindent 10 }}
        {{- end }}
        securityContext:
          {{- toYaml .Values.podSecurityContext | nindent 10 }}
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir:
          sizeLimit: 500Mi
      nodeSelector:
      {{- with .Values.nodeSelector }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
      {{- with .Values.affinity }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      tolerations:
      {{- with .Values.tolerations }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      imagePullSecrets:
      {{- with .Values.image.pullSecrets }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
{{- end }}
