{{- if .Values.serviceAccount.createToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oneview-pagerduty-bridge.serviceAccountName" . }}-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oneview-pagerduty-bridge.labels" . | nindent 4 }}
    component: rbac
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    kubernetes.io/service-account.name: {{ include "oneview-pagerduty-bridge.serviceAccountName" . }}
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.serviceAccount.tokenAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: kubernetes.io/service-account-token
{{- end }}
